In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.6


In [4]:
first_array = np.array([[1,2,3,4,5,6]])
print("First Array:\n", first_array)    

First Array:
 [[1 2 3 4 5 6]]


In [11]:
second_array = np.array([12,13,14], dtype=bool)
print(second_array)
#print("second Array:\n", second_array_int)

[ True  True  True]


In [12]:
# performing Scalar operations on Numpy arrays
a = np.array([5])
print(a)

[5]


In [14]:
# adding some numbers to scalar (a)
print(a + 10)
print(a - 2)
print(a * 2)
print(a / 5)
print(a ** 2)


[15]
[3]
[10]
[1.]
[25]


In [ ]:
# when you add scalar + scalar = scalar
# scalar + vector = vector
# scalar + matrix = matrix
# scalar + tensor = tensor
# Scalar * vector = vector
# Scalar * matrix = matrix
# Scalar * tensor = tensor
# Dot product --> Gen AI


In [17]:
# Vector Operations : collection of scalars
first_vector = np.array([1,2,3,4,5])
second_vector = np.array([6,7,8,9,10])
print(first_vector + second_vector)  # vector + vector = vector
print(first_vector - second_vector)
print(first_vector * second_vector)
print(first_vector / second_vector)
print(first_vector ** second_vector)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]


In [18]:
# array multiplication
first_vector = np.array([1,2,3])
second_vector = np.array([4,5,6])
# result = first_vector.dot(second_vector)
# print("Dot Product:", result)   
result_vector = np.multiply(first_vector, second_vector)
print("Element-wise Multiplication:", result_vector)    

Element-wise Multiplication: [ 4 10 18]


In [20]:
# matrix operations

first_matrix = np.array([[1,2,3],[4,5,6]])
second_matrix = np.array([[7,8,9],[10,11,12]])
print("Matrix Addition:\n", first_matrix + second_matrix)   
print("Matrix Subtraction:\n", first_matrix - second_matrix)
print("Matrix Element-wise Multiplication:\n", first_matrix * second_matrix)
print("Matrix Element-wise Division:\n", first_matrix / second_matrix)

Matrix Addition:
 [[ 8 10 12]
 [14 16 18]]
Matrix Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Matrix Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Matrix Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
# matrix multiplication 

# number of column in 1st matrix = number of rows in 2nd matrix
first_matrix = np.array([1,2,3])
second_matrix = np.array ([12,13,14])
print(first_matrix)
print(second_matrix)

# Array multiplication: 
array_mul = np.multiply(first_matrix , second_matrix)
print("array multiplication is :\n" , array_mul)

# matrix multiplication :
matrix_mul = np.matmul(first_matrix , second_matrix)
print("matrix multiplication is :\n" , matrix_mul)

[1 2 3]
[12 13 14]
array multiplication is :
 [12 26 42]
matrix multiplication is :
 80


In [ ]:
new_array = np.array([[1,2,3] , [4,5,6]])
print ("New Array :\n" , new_array)
print(new_array.shape)
now_array = np.array([[10,20,30], [40,50,60]])  
print ("Now Array:\n", now_array)
print(now_array.shape)

New Array :
 [[1 2 3]
 [4 5 6]]
(2, 3)
Now Array:
 [[10 20 30]
 [40 50 60]]
(2, 3)


In [29]:
# performing matrix multiplication

matrix_mul = np.matmul(new_array , now_array)
print("matrix multiplication:\n" , matrix_mul)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [33]:
# transpose of matrix

tranposed_array = np.transpose(now_array)
print("Transposed array :\n" , tranposed_array)
print(tranposed_array.shape)

Transposed array :
 [[10 40]
 [20 50]
 [30 60]]
(3, 2)


In [34]:
# performing  matrix multiplication 

matrix_mul = np.matmul(new_array , tranposed_array)
print("matrix multiplication:\n" , matrix_mul)

matrix multiplication:
 [[140 320]
 [320 770]]


In [ ]:
# Normal vector / matrix addition , subtraction , division

first_vector = np.array([1,2,3])
second_vector = np.array([6,7,8])

