In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.6


In [ ]:
# Scalar / 0-D array
a= np.array(42)
print(a)

In [ ]:
# Scalar / / Vector / Matrix / Tensor

In [ ]:
# Working with Zeros and ones in numpy arrays
Zeros = np.zeros((3,4)) # (Rows, Columns)
print("Array of Zeros:\n", Zeros)


Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
ones = np.ones((2,5))
print("Array of Ones:\n", ones)


Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# Reshape command in numpy
arr = np.arange(1,13) # n-1
print("Original Array:\n", arr)
reshaped_arr = arr.reshape(3,4) # 3 rows and 4 columns
print("Reshaped array (3*4):\n",reshaped_arr)
print(arr.ndim)
print(arr.shape)

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3*4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
(12,)


In [ ]:
arr.reshape(4,3)
print("reshaped array is:\n", arr.reshape(4,3))
print(arr.ndim) # number of dimensions
print(arr.shape)

reshaped array is:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1
(12,)


In [9]:
arr.reshape(2,2,3)
print("reshaped array is:\n", arr.reshape(2,2,3))
print(arr.ndim) # number of dimensions
print(arr.shape)


reshaped array is:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
(12,)


In [ ]:
# Important commands
# 1. arrange command
# 2. linspace command
# 3. Random command

In [12]:
new_array = np.arange(12,24)  # n-1 , it gives 24 elements 24-12=12 ., 3*4 ,4*3 , 2*6 , 6*2 , 2*2*3 , 2*3*2
new_array.reshape(3,4) 

print("New Array using arrange:\n", new_array)  
print("Dim of new_array:", new_array.ndim)
print("Shape of new_array:", new_array.shape)

# if there is an value error , then look into parameters of reshape function / paranthesis 



New Array using arrange:
 [12 13 14 15 16 17 18 19 20 21 22 23]
Dim of new_array: 1
Shape of new_array: (12,)


In [13]:

new_array.reshape(4,3) 

print("New Array using arrange:\n", new_array)  
print("Dim of new_array:", new_array.ndim)
print("Shape of new_array:", new_array.shape)

New Array using arrange:
 [12 13 14 15 16 17 18 19 20 21 22 23]
Dim of new_array: 1
Shape of new_array: (12,)


In [14]:
#new_array = np.arange(12,24)  # n-1 , it gives 24 elements 24-12=12 ., 3*4 ,4*3 , 2*6 , 6*2 , 2*2*3 , 2*3*2
new_array.reshape(2,2,3)

print("New Array using arrange:\n", new_array)  
print("Dim of new_array:", new_array.ndim)
print("Shape of new_array:", new_array.shape)

New Array using arrange:
 [12 13 14 15 16 17 18 19 20 21 22 23]
Dim of new_array: 1
Shape of new_array: (12,)


In [15]:
#new_array = np.arange(12,24)  # n-1 , it gives 24 elements 24-12=12 ., 3*4 ,4*3 , 2*6 , 6*2 , 2*2*3 , 2*3*2

new_array.reshape(2,3,2) 

print("New Array using arrange:\n", new_array)  
print("Dim of new_array:", new_array.ndim)
print("Shape of new_array:", new_array.shape)

New Array using arrange:
 [12 13 14 15 16 17 18 19 20 21 22 23]
Dim of new_array: 1
Shape of new_array: (12,)


In [26]:
Diff_arr = np.arange(0,12)
print("Diff_arr:\n", Diff_arr)
Diff_arr.reshape(2,2,3) 
print("Diff_arr reshaped:\n", Diff_arr.reshape(2,2,3))

Diff_arr:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Diff_arr reshaped:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
# 1. arrange # 2. linspace # 3. Random


In [28]:
# Linspace : To create an array with evenly spaced values
# Syntax: np.linspace(start, stop, num , endpoint , retstep , dtype)

linspace_array = np.linspace(0, 10, 5, endpoint=False , retstep=True) # 5 values between 0 and 10

In [29]:
lin_arr_1 =np.linspace(0, 1, 5)  # 0 to 1 , 5 values
print("Linspace array:\n", linspace_array)
print("Linspace array 1:\n", lin_arr_1)

Linspace array:
 (array([0., 2., 4., 6., 8.]), np.float64(2.0))
Linspace array 1:
 [0.   0.25 0.5  0.75 1.  ]


In [30]:
lin_arr_2 =np.linspace(1,100, 50) 
print("Linspace array 2:\n", lin_arr_2)

Linspace array 2:
 [  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [ ]:
63.63265306 - 61.6122449285 = 2.020408163

11.10204082 -9.08163265 =2.02040817

In [31]:
# working with Random command

random_array = np.random.rand(3,4)  # 3 rows and 4 columns
print("Random Array:\n", random_array)

Random Array:
 [[0.71433694 0.59349583 0.02742384 0.01807503]
 [0.10608011 0.98808858 0.72063239 0.91260375]
 [0.5047598  0.70810579 0.12093823 0.7525364 ]]
