# Numpy : We use to convert data into numbers / numerical values , Such as a scalar , Vector , Matrix , tensor formats.




In [ ]:
! pip install numpy 
# or ! pip install -qU numpy 


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# importing Numpy library

import numpy as np

In [3]:
# Finding the version of Numpy library
print(np.__version__)


2.2.6


# Que :  what is the Data Structure of Numpy
Ans : the Data Structure of Numpy as know as nd array - which means : n -dimensional array 

In [ ]:
# Creating an array in Numpy
arr=np.array([1,2,3,4,5]) # group of scalars
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# A single number is know as : scalar EX: [5]   ----> has no Dimension [0-Zero]

# A group of scalars is known as vector EX: [1,2,3,4,5] ----> has min 1 Dimension [1-D]

# A group of vectors is know as a Matrix  EX: [ [1,2,3,4,5] , [6,7,8,9,] ] ----> has min of 2 Dimension [2-D]

# A group of Matrix is know as Tensor EX: [] ----> has min of 3 dimension [3-D]

In [ ]:
# Finding more information about a numpy arfray [a- attributes & methods of numpy array]
print("data type of array arr :", arr.dtype)
print("Number of dimension of array arr:" , arr.ndim)
print("Shape of array arr:", arr.shape) # number of rows and columns in the array
print("Size of array arr:", arr.size)   # total number of elements in the array
print("item size of array arr:", arr.itemsize) # size of each element in the array in bytes
print("nbytes of array arr:", arr.nbytes) # total size of the array in bytes (size * itemsize)


print("strides of array arr:", arr.strides) # number of bytes to step in each dimension when traversing an array
print("flags of array arr:", arr.flags) # memory layout of the array
print("base of array arr:", arr.base) # base object if the array is a view of another array
print("T (transpose) of array arr:", arr.T) # transpose of the array
print("flat of array arr:", arr.flat) # flat iterator over the array
print("ctypes of array arr:", arr.ctypes) # ctypes interface of the array
print("data of array arr:", arr.data) # buffer containing the actual elements of the array
print("tolist of array arr:", arr.tolist()) # convert array to a (possibly nested) list
print("view of array arr:", arr.view()) # new view of the array with the same data
print("copy of array arr:", arr.copy()) # new array object with a copy of the data


data type of array arr : int64
Number of dimension of array arr: 1
Shape of array arr: (5,)
Size of array arr: 5
item size of array arr: 8
nbytes of array arr: 40
strides of array arr: (8,)
flags of array arr:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

base of array arr: None
T (transpose) of array arr: [1 2 3 4 5]
flat of array arr: <numpy.flatiter object at 0x000002130B16DCA0>
ctypes of array arr: <numpy._core._internal._ctypes object at 0x000002132ACCA050>
data of array arr: <memory at 0x000002132AC12080>
tolist of array arr: [1, 2, 3, 4, 5]
view of array arr: [1 2 3 4 5]
copy of array arr: [1 2 3 4 5]


In [ ]:
# Creating a 2D array in Numpy
c=np.array([ [1,2,3] , [4,5,6] ]) # group of vectors - matrix
print(c)

[[1 2 3]
 [4 5 6]]


In [9]:
print("data type of array c :", c.dtype)
print("Number of dimension of array c:" , c.ndim)
print("Shape of array c:", c.shape) # number of rows and columns in the array
print("Size of array c:", c.size)   # total number of elements in the array
print("item size of array c:", c.itemsize) # size of each element in the array in bytes
print("nbytes of array c:", c.nbytes) # total size of the array in bytes (size * itemsize)
print("strides of array c:", c.strides) # number of bytes to step in each dimension when traversing an array

data type of array c : int64
Number of dimension of array c: 2
Shape of array c: (2, 3)
Size of array c: 6
item size of array c: 8
nbytes of array c: 48
strides of array c: (24, 8)


In [16]:
#  Creating a 3D array in Numpy
d= np.array([ [ [1,2,3,4] , [5,6,7,8], [ 9,10,11,12] ,[3,4,5,6] ] ])
print(D)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [17]:
print("data type of array d :", d.dtype)
print("Number of dimension of array d:" , d.ndim)
print("Shape of array d:", d.shape) # number of rows and columns in the array
print("Size of array d:", d.size)   # total number of elements in the array
print("item size of array d:", d.itemsize) # size of each element in the array in bytes
print("nbytes of array d:", d.nbytes) # total size of the array in bytes (size * itemsize)

data type of array d : int64
Number of dimension of array d: 3
Shape of array d: (1, 4, 4)
Size of array d: 16
item size of array d: 8
nbytes of array d: 128
